### ISSUE TITLE
how to install it

### ISSUE THREAD

**Issue by ugintl** [shubhamshuklaer/online_trading#2]
I have a php hosting with mysql. How to install this script?

**Comment by shubhamshuklaer** [comment]
I have exams going on right now, so I won't be able to help you much. But I updated the readme to include some info about installing(See at the end).

**Comment by shubhamshuklaer** [comment]
I tested it on my computer just now, using the same instructions as in the end of README and it works. Also note that this is not a polished product, its a course project where we had to make something similar to ebay.

**Comment by ugintl** [comment]
thank you very much for the update and info
