### ISSUE TITLE
Need your help

### ISSUE THREAD

**Issue by ugintl** [shubhamshuklaer/online_trading#3]
Hey Shubham,

Hope your exams going great. Sorry to disturb you

Can you please tell me how to install following script?
https://github.com/watsonrp/consultantsws

I tried to find the file where I can put my database info, but did not find it.

I guess to start using the website, I have to put the database info and import the provided SQL file to my database and I am good to go. Am I right?

**Comment by shubhamshuklaer** [comment]
Well I don't know about that script.
By database info did you mean putting your username password and database host info in project or did you mean creating and importing database.
If first look at the file "incls/connector.php" in the link you gave
if second use phpMyAdmin.

**Comment by swapagarwal** [comment]
Hey @ugintl, I see you're new to GitHub.
Most software projects have a place to discuss and keep track of tasks, enhancements, and bugs. GitHub’s tracker is called Issues, and has its own section in every repository.
I'm closing this as your issue belongs [here](https://github.com/watsonrp/consultantsws/issues/). Feel free to include @username to summon anyone there.

**Comment by ugintl** [comment]
ok
